language: ruby
rvm:
  - 2.2.4
branches:
  only:
  - master
env:
  global:
  - secure: IQ6i8lFkNsZiUQattdrQt10/I3kalGOlxOAaFFsYgs4EvuDfCGyPvtSXe3BUGfCFY+6P7J18n6nPIuARZ3PZBMMdx21h2P770gB4bpZLc0U0c3quAL8NcR4Ue1X5mH9hZN3IjRFgUcFzI9zeq3UolxMR7YWJgO4VJVwfg/ftky0BS/P7uInRx20lCD2tiBgLDzvziqRXFIcpIjyEI38ioWMcuKZUDSsaGdOzCs5pw0Gzp9gQm7FoDU04n1jbsMopUUsuJXOZ7ZBKDDTIiTVb1tqMJasf5SC8DUcA2FZTxWnMYCy3BKRsPjClaNiVoaO7GXKd40z6F9mXzZn2xI7U7sS2BbGLWU+LsTo4yS0OYIVHpTj4YsBOLKv9pK4c5ECyU/fF8kA2FoWG0wrH7lphNmcZS/t2EoxR+FPyzAFojkQhWppo/GIQuy59Tv2EYkJG0DmoiOZiG34AKHTEJB5QM4A0tFnFwGWht/RoyHXI8p1eEWxPPtpjVqcLOPASPNZIPfmwUj9s5z9F6oVg3Vm3r5mEruuvuiKVtVF1Oi0HW7QA2P8NYplzydWXOl++SAkvaT+ybh/9sTCW1HXl3qH7FJWWS/6yBKKaxD5o2PLGNCKzcyzRp6JTM0/tNgNiBJmWvos2i/Tn4Q60KAB1nJ15iY+2cE8dI/bOPBQzeaCx244=
  - secure: eAOU7dcCz/HQndwKZmy+v4qAyoBxYfaBYnM3siaSi+KWSubj9vMFT8ivLtPiLqf8Ou0fKQ/JLY+mOL0TKqUxmFSy35vVFqF8D9kQ21JSNveaHeqRX4Bhmng/Y48mu4q7tvRuFCYvvXW+zA4KC4vKX6lY9f+/rX9GpuPnZbtZFywGIASi18FwnFqJQRolHhBRcO7s0MJJT2m+pBCd8SM04BwRQy7kvt7ryI8NwONiSueWmGcnvi/CBVu0AAcg9qFwj/eeeIlWjCloR1t/gfmIrjp454Wms/4t/++nVM0BGo0Zw7gKpcKEa6KPcEu1uvUbooYsJGs6RKwEn1KxHBdHz2j7Wes/V/cgVUAXP5LVEKBnqJxM0bgZvaux6JIpRBFCKRlYj8mKcoMnsIEiHba36dXuExovnKlvuDzDESf8JXew3fhKJNk8xR7bzq7NCQdvOxWV97qrS/QYoboTP3/vZm1Omfu4InzHLy9ygArgF7LDyUGkVK7bJF4HnVb8Y3j5DxHDW+4YYeZgdFawitY+yAXoNRs+BokQ0dtgCnmdiItn73dbLdSAi5BvpVUN0A8nyFELBK0uCBblPEcRubER3+EWrA9jdPRAG07UkXD9Qt9oQ+JJVe3p+jbxtLWE0m+gc4EMxKauSawghFWoIVRsOI1WO3M6cgCAuP9Reu7HuWI=
after_success:
  - ./deploy.sh
